export const Genders = [
    "Feminino",
    "Masculino",
    "Outro",
]

export const Occupations = [
    "Usuário",
    "Designer",
    "Desenvolvedor",
    "Engenheiro de Software",
    "Analista de Sistemas",
    "Arquiteto de Soluções",
    "Especialista em Usabilidade",
    "Consultor de Tecnologia",
    "Gestor de Produto",
    "Pesquisador de UX",
    "Designer de Interface",
    "Desenvolvedor Front-end",
    "Designer Gráfico",
    "Product Owner",
    "Gerente de Projetos de TI",
    "Desenvolvedor Full Stack",
    "Analista de Qualidade de Software",
    "Especialista em Acessibilidade",
    "Analista de Dados",
    "Designer de Interação",
    "Especialista em Desenvolvimento Web",
    "Arquiteto de Informação",
    "Desenvolvedor Mobile",
    "Gestor de Experiência do Cliente",
    "Especialista em Design Digital",
    "Engenheiro de Dados",
    "Consultor de UX/UI",
    "Desenvolvedor de Aplicações",
    "Especialista em Design de Produtos",
    "Analista de Negócios",
    "Especialista em Inteligência Artificial",
    "Outro"
  ]